// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY5eOt0aVrAgLhp3TDk4Xzu10jJJzjuvs',
    appId: '1:298892778019:web:3b047227a8e1e9d5422f96',
    messagingSenderId: '298892778019',
    projectId: 'loginf-7fb8f',
    authDomain: 'loginf-7fb8f.firebaseapp.com',
    storageBucket: 'loginf-7fb8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkN8H341JvbuLlKO3-jabK58BTJruzw2E',
    appId: '1:298892778019:android:d6d87cf5c9e1a647422f96',
    messagingSenderId: '298892778019',
    projectId: 'loginf-7fb8f',
    storageBucket: 'loginf-7fb8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4EuAJC1mvRM7cxjYNXwx0DrtaVWXa6es',
    appId: '1:298892778019:ios:53516dcbce19c2cb422f96',
    messagingSenderId: '298892778019',
    projectId: 'loginf-7fb8f',
    storageBucket: 'loginf-7fb8f.appspot.com',
    iosClientId: '298892778019-b1k82b8akbj7guqqq9sdutriq9q7q6gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4EuAJC1mvRM7cxjYNXwx0DrtaVWXa6es',
    appId: '1:298892778019:ios:c8df39d22b71e763422f96',
    messagingSenderId: '298892778019',
    projectId: 'loginf-7fb8f',
    storageBucket: 'loginf-7fb8f.appspot.com',
    iosClientId: '298892778019-jmtb2vmlv17o0j31mt0vhri3hs33pcrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage01.RunnerTests',
  );
}
